import '/node_modules/@javascribble/quantum/source/main.js';
import '/node_modules/@javascribble/quantum-tabs/source/main.js';
import '/node_modules/@javascribble/quantum-layout/source/main.js';
import '/node_modules/@javascribble/quantum-region/source/main.js';
import '/node_modules/@javascribble/quantum-canvas/source/main.js';
import '/node_modules/@javascribble/quantum-canvas/source/extensions/images.js';
import '/node_modules/@javascribble/quantum-input/source/main.js';
import '/node_modules/@javascribble/quantum-context/source/main.js';
import '/node_modules/@javascribble/quantum-menu/source/main.js';
import '/node_modules/@javascribble/quantum-tree/source/main.js';
import '/node_modules/@javascribble/quantum-engine/source/main.js';
import '/node_modules/@javascribble/quantum-engine/source/plugins/image.js';
import '/node_modules/@javascribble/quantum-engine/source/presets/engine.js';
import '/source/extensions/prototypes.js';
import '/source/extensions/resources.js';
import '/source/plugins/animation.js';
import '/source/plugins/architecture.js';
import '/source/main.js';
import '/test/game.js';

document.body.style.visibility = 'visible';